#!/bin/bash
#SBATCH --ntasks 1 # Number of cores requested
#SBATCH -t 0-5:59:59 # Runtime in minutes
#SBATCH -p blackhole # Partition to submit to
#SBATCH --mem-per-cpu=4G
#SBATCH -o out.out # Standard out goes to this file
#SBATCH -e err.err # Standard err goes to this filehostname

# make the hostfile
srun hostname -s > hostfile4
sleep 5

module restore
julia make_summary_ha.jl


