#!/bin/bash
#SBATCH --account=def-abroderi
#SBATCH --ntasks=360
#SBATCH --mem-per-cpu=4096M
#SBATCH --time=0-23:59
#SBATCH -o "OUT3"
#SBATCH -e "ERR3"
# make the hostfile
srun hostname -s > hostfile3
sleep 5

julia --project=@. --machine-file ./hostfile3 runstacker_grmhd_gr.jl 3


