#!/bin/bash
#SBATCH --account=def-abroderi
#SBATCH --ntasks=30
#SBATCH --mem-per-cpu=4096M
#SBATCH --time=0-11:59
#SBATCH -o "OUT3"
#SBATCH -e "ERR3"
# make the hostfile
srun hostname -s > hostfileconv
sleep 5

julia --project=@. --machine-file ./hostfileconv runstacker_grmhd_gr_conv.jl 4


